* <2018-10-22>: Etienne
** 2.2.1 Parameters
  - Focus on geometrical parameters
  - Energy and TOF selection will be mentioned in the introduction when presenting the objectives of the paper and the section "Monte Carlo simulation"
**  Section 2.2.2
  - Adding of the effective slit opening
  - remove of the FRP definition mentioned in the previous subsection 2.1 "Features of PG profiles"
  - New definition of the collection efficiency (CE) :
    - the Linear Collection Efficiency defined in Frauke's manuscript is actually a Collection Efficiency. It is indeed an adimensionnal quantity and it can be compared to the efficiency obtained from MC (although we do no expect a very good agreement).
    - CE is defined as the product of geometrical detection efficiency by the FOV factor a new quantity that accounts for the ratio between the FOV of a detection unit and the camera pitch
** Section 2.3
- I tried to make it clear the 2 setups of MC simulations
  - the MPS and KES prototypes
  - Setup for geometrical consideration verifications: same absorber and same event selections (energy and TOF selections)
- => 2 distinct paragraphs for each setup in the following sections:
    - 2.3.2 PG camera modeling
    - 2.3.3 Background modeling
    - 2.5 Figures of merit
** Section 2.3.2
- Change of the energy selection for the analytical model verification: it was 3-6 MeV and we would be interesting to use E>1 MeV because then when we move to the prototypes comparison, we can see the influence of:
  - TOF for MPS
  - a change of energy selection for KES
  - => This is a good opportunity to show the influence of some important parameters of the cameras performances.
I tried to put some emphasis on that with a new table.
** Section 2.5
  - Remove of the beginning of the section that refers to the "verification of the cameras" in Appendix
  - Change of the sentence on the linear collection efficiency that was mentioning background. It does not really make sense to talk about background here since the detection efficiency is defined for gamma rays (i.e. the signal). 
** Section 3.1.3 
- Remove the section title since the content is actually related to spatial resolution, not Falloff retrieval precision


* TODO
- Replace "geometrical considerations" by "Analytical model"
- Renvoyer un mail à Frauke
